name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "環境を選んでください"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production
      version:
        description: "バージョンを入力してください"
        required: true
        type: string
      environment_input:
        description: "環境入力"
        type: environment
      number_input:
        description: "数値入力"
        type: number

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show parameters
        run: |
          echo "Deploy environment: ${{ github.event.inputs.environment }}"
          echo "Deploy version: ${{ github.event.inputs.version }}"
