name: Matrix Practice

on:
  workflow_dispatch: # 手動実行用トリガー

jobs:
  example-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Print current environment
        run: |
          echo "Running on ${{ runner.os }}"
          echo "Architecture: ${{ runner.arch }}"
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Linux build
        if: runner.os == 'Linux'
        run: make

      - name: Windows build
        if: runner.os == 'Windows'
        run: ./build.ps1

      - name: macOS build
        if: runner.os == 'macOS'
        run: make
