name: Run Composite Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # コンポジットアクションを使用
      - name: Setup Development Environment
        uses: ivis-sunqianshu/learn-github-actions/my-composite-action@v1 # owner-name/repo-name@ref の形式
        with:
          node-version: "20"
          python-version: "3.9"

      # セットアップされた環境を使用
      - name: Build Project
        run: npm run build
