name: Run Composite Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # コンポジットアクションを使用
      - name: Setup Development Environment
        uses: ./.github/actions/my-composite-action
        with:
          node-version: "20"
          python-version: "3.9"

      # セットアップされた環境を使用
      - name: Build Project
        run: npm run build
